<?php

namespace Kodilab\LaravelFilters\Tests;

abstract class TestCase extends \Orchestra\Testbench\TestCase
{
    protected $test_files_path;

    protected $factories_path;

    protected $test_model_name = 'test_model';

    protected $test_model_table = 'test_models';

    protected $fallback_locale;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->artisan('migrate')->run();

        $this->loadMigrationsFrom(__DIR__ . DIRECTORY_SEPARATOR . 'migrations');
    }

    protected function getPackageProviders($app)
    {
        return [
            \Kodilab\LaravelFilters\FiltersProvider::class
        ];
    }

    protected function assertSQLContainsString(string $string, string $sql)
    {
        if (env('DB_CONNECTION') === 'mysql') {

            $string = $this->escapeForMySQL($string);
            $this->assertStringContainsString($string, $sql);

        } else {

            $this->assertStringContainsString($string, $sql);

        }
    }

    protected function assertSQLNotContainsString(string $string, string $sql)
    {
        if (env('DB_CONNECTION') === 'mysql') {

            $string = $this->escapeForMySQL($string);
            $this->assertStringNotContainsString($string, $sql);

        } else {

            $this->assertStringNotContainsString($string, $sql);

        }
    }

    private function escapeForMySQL(string $string)
    {
        return str_replace("\"", "`", $string);
    }
}
