<?php

namespace Kodilab\LaravelFilters\Tests\Unit;

use Kodilab\LaravelFilters\Tests\TestCase;

class FilterTest extends TestCase
{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function test_tue_is_true()
    {
        $this->assertTrue(true);
    }
}
